spring:
  profiles:
    include:
      - secrets
  data:
    mongodb:
      host: localhost
      port: 27017
  mongodb:
    embedded:
      version: 4.4.0
logging:
  level:
    root: WARN
    org.springframework.security: DEBUG
  file:
    name: TacoCloud.log