spring:
  profiles:
    include:
      - secrets
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://authserver:9000/oauth2/jwks
  data:
    mongodb:
      host: localhost
      port: 27017
    rest:
      base-path: /data-api
  mongodb:
    embedded:
      version: 4.4.0
logging:
  level:
    root: WARN
    org.springframework.security: DEBUG
  file:
    name: TacoCloud.log
taco:
  orders:
    pageSize: 5